INSERT INTO BOARDS(BOARD_ID, BOARD_NAME) VALUES (1, 'board 1')
INSERT INTO BOARDS(BOARD_ID, BOARD_NAME) VALUES (2, 'board 2')

INSERT INTO COLUMNS(COLUMN_ID, COLUMN_NAME, BOARD_ID) VALUES (1, 'In progress', 1)
INSERT INTO COLUMNS(COLUMN_ID, COLUMN_NAME, BOARD_ID) VALUES (2, 'Done', 1)
INSERT INTO COLUMNS(COLUMN_ID, COLUMN_NAME, BOARD_ID) VALUES (3, 'To do', 2)

INSERT INTO ROLES(ROLE_ID, ROLE_NAME) VALUES (1, 'QA')
INSERT INTO ROLES(ROLE_ID, ROLE_NAME) VALUES (2, 'Developer')
INSERT INTO ROLES(ROLE_ID, ROLE_NAME) VALUES (3, 'BA')

INSERT INTO TICKETS(TICKET_ID, TICKET_TITLE, TICKET_DESCRIPTION, COLUMN_ID) VALUES (1, 'info 1', 'desc 1', 1)
INSERT INTO TICKETS(TICKET_ID, TICKET_TITLE, TICKET_DESCRIPTION, COLUMN_ID) VALUES (2, 'info 2', 'desc 2', 2)
INSERT INTO TICKETS(TICKET_ID, TICKET_TITLE, TICKET_DESCRIPTION, COLUMN_ID) VALUES (3, 'info 3', 'desc 3', 1)

INSERT INTO USERS(USER_ID, LOGIN, PASSWORD) VALUES (1, 'issue', '123')

INSERT INTO USERS_BOARDS(USER_ID, BOARD_ID, ROLE_ID) VALUES (1, 1, 2)
INSERT INTO USERS_BOARDS(USER_ID, BOARD_ID, ROLE_ID) VALUES (1, 2, 1)